ERROR [2025-03-02 17:30:19]
	File: d:\Projects\DownloadManager\desktop_app\app.py
	Function: set_png_icon
	Line: 398
	Message: One of the PNG icons is missing
	Called from:
		File: d:\Projects\DownloadManager\desktop_app\app.py
		Function: create_home_frame
		Line: 184
ERROR [2025-03-02 17:30:04]
	File: d:\Projects\DownloadManager\desktop_app\app.py
	Function: set_png_icon()
	Line: 398
	Message: One of the PNG icons is missing
	Called from:
		File: d:\Projects\DownloadManager\desktop_app\app.py
		Function: create_home_frame()
		Line: 184
ERROR [2025-03-02 17:28:15]
	File: d:\Projects\DownloadManager\desktop_app\app.py
	Function: set_png_icon()
	Line: 398
	Message: One of the PNG icons is missing
	Called from:
		File: d:\Projects\DownloadManager\desktop_app\app.py
		Function: create_home_frame(
		Line: 184
ERROR [2025-03-02 17:28:02]
	Function name: set_png_icon
	File: d:\Projects\DownloadManager\desktop_app\app.py
	Line: 398
	Message: One of the PNG icons is missing
	Called from:
		File: d:\Projects\DownloadManager\desktop_app\app.py
		Function: create_home_frame
		Line: 184
ERROR [2025-03-02 17:24:35]
	Function name: set_png_icon
	Function file: d:\Projects\DownloadManager\desktop_app\app.py
	Line number: 398
	Message: One of the PNG icons is missing
	Called from:
		File: d:\Projects\DownloadManager\desktop_app\app.py
		Function: create_home_frame
		Line: 184
ERROR [2025-03-02 15:45:15]
	Function name: set_png_icon
	Function file: d:\Projects\DownloadManager\desktop_app\app.py
	Line number: 444
	Message: No icon name is given
ERROR [2025-03-02 15:45:15]
	Function name: get_icon_path
	Function file: d:\Projects\DownloadManager\desktop_app\app.py
	Line number: 420
	Message: The icon PNG file 'downloads_dark.png' does not exist
ERROR [2025-03-02 15:45:15]
	Function name: get_icon_path
	Function file: d:\Projects\DownloadManager\desktop_app\app.py
	Line number: 420
	Message: The icon PNG file 'downloads_light.png' does not exist
ERROR [2025-03-02 14:58:12]
	Function name: set_button_icon
	Function file: d:\Projects\DownloadManager\desktop_app\app.py
	Line number: 82
	Message: The button icon file 'home_dar' does not exist
ERROR [2025-03-02 14:55:22]
	Function name: set_button_icon
	Function file: d:\Projects\DownloadManager\desktop_app\app.py
	Line number: 79
	Message: The path to the button icon file does not exist
ERROR [2025-03-02 14:54:33]
	Function name: set_button_icon
	Function file: d:\Projects\DownloadManager\desktop_app\app.py
	Line number: 79
	Message: The path to the button icon file does not exist
ERROR [2025-03-02 14:52:08]
	Function name: set_button_icon
	Function file: d:\Projects\DownloadManager\desktop_app\app.py
	Line number: 81
	Message: The path to the button icon file does not exist
INFO [2025-03-02 14:50:50]
	Function name: set_button_icon
	Function file: d:\Projects\DownloadManager\desktop_app\app.py
	Line number: 80
	Message: The path to the button icon file does not exist
ERROR [2025-02-27 12:27:09]
	Function name: get_dictionary_stats
	Function file: d:\Projects\Document Manager\backend\dir_operations.py
	Line number: 132
	Code: "creation_time": datetime.fromtimestamp(dir_path.stat().st_birthtime).strftime("%Y-%m-%d %H:%M:%S")
	Message: module 'datetime' has no attribute 'fromtimestamp'
ERROR [2025-02-27 12:26:16]
	Function name: get_dictionary_stats
	Function file: d:\Projects\Document Manager\backend\dir_operations.py
	Line number: 130
	Code: "size": utils.format_bytes(directory_info['byte_size']),
	Message: cannot access local variable 'directory_info' where it is not associated with a value
ERROR [2025-02-27 12:05:02]
	Function name: move
	Function file: C:\Users\adame\AppData\Local\Programs\Python\Python313\Lib\shutil.py
	Line number: 854
	Code: raise Error("Destination path '%s' already exists" % real_dst)
	Message: Destination path 'D:\test1\b' already exists
ERROR [2025-02-27 11:14:44]
	Function name: directory_secure_delete
	Function file: d:\Projects\Document Manager\backend\dir_operations.py
	Line number: 65
	Code: if is_directory_empty():
	Message: is_directory_empty() missing 1 required positional argument: 'directory_path'
ERROR [2025-02-27 11:12:32]
	Function name: directory_secure_delete
	Function file: d:\Projects\Document Manager\backend\dir_operations.py
	Line number: 65
	Code: if is_directory_empty():
	Message: is_directory_empty() missing 1 required positional argument: 'directory_path'
